// AUTO-GENERATED by the author-learning-topics workflow (authored + fact-checked).
// Edit content via the workflow, not by hand. 7 topics, 36 teach steps, 36 quizzes.
import type { LearnTopic } from "./learning";

export const LEARNING_TOPICS: LearnTopic[] = [
  {
    "id": "t-service",
    "icon": "🏪",
    "title": "Service Entity Costing",
    "desc": "Master how firms cost time and expertise — no warehouses, no widgets, just the work.",
    "steps": [
      {
        "type": "teach",
        "title": "What even is a service firm?",
        "body": "Here's the big mental shift: a service firm doesn't sell you a thing you can hold — it sells expertise and time. There's no box, no inventory on a shelf. When you pay a lawyer or a hairdresser, you're paying for what they DO, not for an object you take home.",
        "analogy": "Think Spotify vs a record store. The record store hands you a physical CD; Spotify just gives you access to the skill and effort of streaming music to your ears. Service firms are all 'Spotify' — output you experience, not own."
      },
      {
        "type": "quiz",
        "question": "What does a service firm fundamentally deliver to customers?",
        "options": [
          "Physical products held in inventory",
          "Expertise and time, not a physical product",
          "Raw materials it has purchased and resold",
          "Manufactured goods built to order"
        ],
        "answer": 1,
        "correctMsg": "Exactly! Service firms sell expertise and time — there's no physical product on a shelf. You're paying for what they do.",
        "wrongMsg": "Almost — the key is that service firms deliver expertise and time, NOT a physical product. There's no inventory you take home; you're buying the work itself."
      },
      {
        "type": "teach",
        "title": "The three flavours of service firm",
        "body": "Services come in three types based on contact time and volume. A PROFESSIONAL service firm has high contact time, few customers, and is highly customised — think lawyers and consultants. A SERVICE SHOP sits in the middle: medium contact, medium volume, like a car repair shop. And MASS SERVICE is low contact, high volume, very standardised — retail banks and public transport.",
        "analogy": "It's like haircuts. A bespoke celebrity stylist who spends three hours on one client = professional. Your regular neighbourhood barber = service shop. A quick-cut chain doing 80 trims a day off a price list = mass service."
      },
      {
        "type": "quiz",
        "question": "A retail bank serving thousands of customers with standardised, low-contact transactions is an example of which type?",
        "options": [
          "Professional service firm",
          "Service shop",
          "Mass service",
          "Manufacturing firm"
        ],
        "answer": 2,
        "correctMsg": "Spot on! Low contact + high volume + standardised = mass service. Retail banks and transport are textbook examples.",
        "wrongMsg": "Not quite — high volume, low contact, and standardised points to MASS SERVICE (retail banks, transport). Professional firms are the opposite: high contact, few customers, highly customised."
      },
      {
        "type": "teach",
        "title": "The 'professional' end of the spectrum",
        "body": "Professional service firms are the high-touch, low-volume end: lots of contact time, only a handful of customers, and every job tailored to that client. A consultant might spend weeks on one company's problem. The work is bespoke, not churned out.",
        "analogy": "Like a tailor making a custom suit fitted to your exact body versus grabbing one off the rack. Tons of one-on-one time, a few clients, totally customised — that's the professional service firm."
      },
      {
        "type": "quiz",
        "question": "Which combination best describes a professional service firm (e.g. a consultant)?",
        "options": [
          "Low contact time, high volume, standardised",
          "High contact time, few customers, highly customised",
          "Medium contact, medium volume",
          "No customer contact, fully automated"
        ],
        "answer": 1,
        "correctMsg": "Yes! High contact, few customers, highly customised — that's the professional service firm in a nutshell.",
        "wrongMsg": "Gently rewinding: professional service firms are HIGH contact, FEW customers, and HIGHLY customised. Low contact + high volume + standardised is mass service instead."
      },
      {
        "type": "teach",
        "title": "The service value chain (mind the trap!)",
        "body": "A service firm's value chain runs: R&D/design, then marketing, then delivery, then customer support. Here's the classic exam trap — there is NO purchasing of raw materials, because services don't make physical products. If you see 'purchasing raw materials' listed as a service value chain step, that's the wrong answer.",
        "analogy": "Picture Netflix: they design shows (R&D), market them, deliver via streaming, and run support if your login breaks. At no point do they buy timber or steel — there are no raw materials to purchase, just like any service firm."
      },
      {
        "type": "quiz",
        "question": "Which of these is NOT part of a service firm's value chain?",
        "options": [
          "R&D / design",
          "Marketing",
          "Purchasing of raw materials",
          "Customer support"
        ],
        "answer": 2,
        "correctMsg": "Nailed it — and you dodged the classic trap! Services don't buy raw materials. The chain is R&D/design, marketing, delivery, and customer support.",
        "wrongMsg": "Careful, this is the famous trap: 'purchasing of raw materials' is NOT in a service value chain (no physical products to make). The real steps are R&D/design, marketing, delivery, and customer support."
      },
      {
        "type": "teach",
        "title": "When job costing fits a service",
        "body": "Job costing tracks the cost of each job separately. For services, you use it when the work is distinct/customised and produced in LOW volume — so each job is unique enough to track on its own. High-volume, standardised services don't suit job costing because the jobs are basically identical.",
        "analogy": "It's like a custom tattoo artist tracking the time, ink, and design effort for each individual client's unique piece — every job is its own little project with its own cost tag, because no two are the same."
      },
      {
        "type": "quiz",
        "question": "Job costing is most appropriate for a service when the work is...",
        "options": [
          "Standardised and produced in very high volume",
          "Distinct/customised and produced in low volume, tracked per job",
          "Identical for every customer so no tracking is needed",
          "Always free of any direct labour"
        ],
        "answer": 1,
        "correctMsg": "Perfect! Job costing shines when services are distinct/customised and low-volume, so each job gets tracked separately.",
        "wrongMsg": "Let's reset that: job costing fits DISTINCT, customised, LOW-volume services where each job is tracked separately. Standardised high-volume work is the opposite of when you'd use it."
      }
    ]
  },
  {
    "id": "t-relevant",
    "icon": "⚖️",
    "title": "Relevant Costs",
    "desc": "Learn the one filter that cuts through messy numbers so you only decide on what actually matters.",
    "steps": [
      {
        "type": "teach",
        "title": "The Two-Part Test",
        "body": "Here's the whole secret, and it's gentler than it looks: a cost is RELEVANT only if it ticks BOTH boxes. It has to be a FUTURE cost (still ahead of you, not already spent) AND it has to DIFFER between your options. If a number is the same no matter what you choose, it can't possibly tip the decision, so you ignore it. Master this one filter and half of managerial accounting becomes easy.",
        "analogy": "Picking a Friday night plan: the cost of the Netflix subscription you already pay either way doesn't matter. What matters is the stuff that changes between 'cinema' and 'stay in' — the ticket, the Uber, the popcorn."
      },
      {
        "type": "quiz",
        "question": "For a cost to be relevant to a decision, it must be...",
        "options": [
          "A future cost AND differ between the alternatives",
          "A large cost AND already paid",
          "A future cost OR a past cost, as long as it's big",
          "The same across every alternative you're considering"
        ],
        "answer": 0,
        "correctMsg": "Exactly! Both boxes ticked: it lies in the future AND it changes depending on what you pick. If either fails, it's irrelevant.",
        "wrongMsg": "Not quite — size and 'already paid' don't matter. A relevant cost must be in the FUTURE and must DIFFER between the alternatives. Both conditions, every time."
      },
      {
        "type": "teach",
        "title": "Sunk Costs Are Ghosts",
        "body": "A sunk cost is money that's already gone — spent, signed, done. Because it's in the past, it can never differ between your future choices, so it's NEVER relevant. The hard part isn't the logic, it's your feelings: we hate 'wasting' what we've already paid. But the money doesn't come back no matter what you decide next, so let the ghost go.",
        "analogy": "You bought a $15 cinema ticket, but 20 minutes in the film is terrible. The $15 is gone whether you stay or leave — so the only real question is: more misery, or freedom? Walk out."
      },
      {
        "type": "quiz",
        "question": "You already spent $80,000 developing a product last year. In deciding whether to keep selling it, that $80,000 is...",
        "options": [
          "Relevant, because it was a huge amount of money",
          "Sunk and therefore irrelevant to the decision",
          "Relevant, because you need to earn it back",
          "Relevant only if it was more than this year's costs"
        ],
        "answer": 1,
        "correctMsg": "Yes! It's already spent, so it's the same under every future option — a sunk cost, irrelevant. 'Earning it back' is a feeling, not a relevant cost.",
        "wrongMsg": "Gently — that $80,000 is already gone no matter what you choose next, so it can't differ between alternatives. That makes it a sunk cost: irrelevant. The urge to 'earn it back' is the sunk cost trap."
      },
      {
        "type": "teach",
        "title": "Make or Buy: Only Avoidable Costs Count",
        "body": "When deciding whether to make a part yourself or buy it from a supplier, the max price you'd accept per unit equals the costs you'd actually ESCAPE by stopping production: variable cost + AVOIDABLE fixed cost. Allocated or unavoidable overhead keeps haunting you whether you make or buy, so it's irrelevant. Example: 100,000 units, variable $300,000, direct fixed $100,000 (80% avoidable), allocated OH $50,000 — avoidable = 300,000 + 0.8×100,000 = $380,000, ÷ 100,000 = $3.80. So buy only if the supplier's price is below $3.80.",
        "analogy": "Cancelling your gym membership only saves what you actually stop paying — the monthly fee. Your flatmate's rent gets charged to you either way, so it doesn't belong in the 'should I quit the gym?' maths."
      },
      {
        "type": "quiz",
        "question": "Using the example (variable $300,000; direct fixed $100,000 with 80% avoidable; allocated OH $50,000; 100,000 units), the highest price per unit you'd pay to buy is...",
        "options": [
          "$4.50 (everything divided by units)",
          "$3.00 (just the variable cost)",
          "$3.80 (variable + avoidable fixed, per unit)",
          "$4.00 (variable + all direct fixed)"
        ],
        "answer": 2,
        "correctMsg": "Spot on! 300,000 + 0.8×100,000 = 380,000 over 100,000 units = $3.80. Allocated OH and the unavoidable 20% are excluded because they don't change.",
        "wrongMsg": "Close, but watch the avoidable bit: only 80% of the direct fixed is escapable, and allocated OH never goes away. So 300,000 + 0.8×100,000 = 380,000 ÷ 100,000 = $3.80."
      },
      {
        "type": "teach",
        "title": "Special Orders: Just Cover the Extra Cost",
        "body": "A one-off order at a low price feels scary, but if you have SPARE CAPACITY, the only thing that matters is the incremental (variable) cost of making those extra units. Your existing fixed costs are already being paid by your normal business, so they're irrelevant here. Accept the special order whenever the price offered is ABOVE that incremental cost — even if it's below your usual price.",
        "analogy": "Your band already booked and paid for the venue tonight. A last-minute request for 10 extra tickets? You'd say yes for almost anything above the cost of printing them — the hall's rent is covered regardless."
      },
      {
        "type": "quiz",
        "question": "You have spare capacity. A customer offers a price per unit that's below your normal price but above your variable cost per unit. You should...",
        "options": [
          "Reject it — the price is below your normal selling price",
          "Reject it unless it also covers a share of fixed costs",
          "Accept it — the price exceeds incremental cost, so it adds profit",
          "Accept only if it covers variable plus allocated overhead"
        ],
        "answer": 2,
        "correctMsg": "Yes! With spare capacity, fixed costs are already covered and irrelevant. Any price above incremental (variable) cost adds to profit — take it.",
        "wrongMsg": "Have another look: with spare capacity your fixed costs don't change, so they're irrelevant. As long as the price beats the incremental (variable) cost, the order adds profit — accept it."
      },
      {
        "type": "teach",
        "title": "Sell Now or Process Further?",
        "body": "When a product can be sold at the split-off point OR processed further and sold for more, the joint cost spent BEFORE split-off is sunk — ignore it completely. Just compare the EXTRA revenue from processing against the EXTRA processing cost. Example: 5,000 units sell for $20 at split-off, OR process for +$20,000 and sell at $25: (25−20)×5,000 − 20,000 = $5,000 better off. Process further! (The $80,000 joint cost is irrelevant — it's already spent either way.)",
        "analogy": "You bought raw timber (already paid). Now: sell the planks as-is, or spend a weekend sanding and varnishing to sell them for more? Only weigh the varnish + your time against the higher price. The timber's cost is history."
      },
      {
        "type": "quiz",
        "question": "5,000 units sell for $20 now, or process further for +$20,000 and sell at $25. Joint cost so far is $80,000. The right move is...",
        "options": [
          "Sell now — the $80,000 joint cost makes processing a loss",
          "Process further — extra revenue $25,000 beats extra cost $20,000 by $5,000",
          "Indifferent — both give the same profit",
          "Sell now — $25,000 extra revenue minus $80,000 joint cost is negative"
        ],
        "answer": 1,
        "correctMsg": "Exactly! Extra revenue (25−20)×5,000 = $25,000, minus extra cost $20,000 = $5,000 gain. The $80,000 joint cost is sunk and ignored — process further.",
        "wrongMsg": "Careful with that $80,000 — it's a joint cost already spent, so it's sunk and irrelevant. Only compare the extra: $25,000 extra revenue − $20,000 extra cost = $5,000 gain. Process further."
      }
    ]
  },
  {
    "id": "t-constraint",
    "icon": "🚧",
    "title": "Constrained Resources",
    "desc": "When one thing runs out, the product that \"looks\" best on paper often loses — here's how to actually win.",
    "steps": [
      {
        "type": "teach",
        "title": "What's a constraint, anyway?",
        "body": "A constraint is the one resource you just don't have enough of — machine hours, labour hours, a special material. When that resource is the bottleneck, you literally can't make everything customers want. So the real question stops being 'what should we make?' and becomes 'how do we squeeze the most profit out of the scarce thing?'",
        "analogy": "Think of a tiny espresso machine at a packed café. You've got endless customers, but only so many shots per hour. The machine — not demand — decides how much you can sell."
      },
      {
        "type": "quiz",
        "question": "In a constrained-resource problem, what is the 'constraint'?",
        "options": [
          "The product with the highest selling price",
          "The single resource you don't have enough of to meet all demand",
          "The product customers want least",
          "The total amount of money you can spend"
        ],
        "answer": 1,
        "correctMsg": "Exactly! The constraint is the scarce resource — the bottleneck — that caps how much you can produce, no matter how strong demand is.",
        "wrongMsg": "Not quite — the constraint isn't about price or popularity. It's the one resource (like machine hours) that's in short supply and limits how much you can make."
      },
      {
        "type": "teach",
        "title": "Don't rank by CM per unit",
        "body": "Your instinct says 'make the product with the highest contribution margin per unit — that's the most profitable one!' But that's a trap when a resource is scarce. CM per unit ignores how much of the precious bottleneck each product gobbles up. A juicy $10 margin isn't so juicy if it eats 5x the scarce resource.",
        "analogy": "It's like picking your road-trip snacks by tastiness alone, ignoring that the giant cake takes up your whole backpack. Yum per snack isn't the point — yum per inch of bag space is."
      },
      {
        "type": "quiz",
        "question": "Why is ranking products by contribution margin per unit a mistake when a resource is limited?",
        "options": [
          "CM per unit is always inaccurate",
          "It ignores how much of the scarce resource each product consumes",
          "Contribution margin doesn't matter at all under constraints",
          "Higher CM products are always unprofitable"
        ],
        "answer": 1,
        "correctMsg": "Spot on! CM per unit tells you nothing about how greedily a product uses the bottleneck — so it can steer you wrong.",
        "wrongMsg": "Close, but CM still matters — the issue is that CM per unit ignores how much of the scarce resource each product uses up. That's the missing piece."
      },
      {
        "type": "teach",
        "title": "Rank by CM per unit of the scarce resource",
        "body": "Here's the fix: divide each product's contribution margin by the amount of the scarce resource it uses. That gives you CM per machine hour (or per labour hour, etc.) — the profit you earn from each precious unit of the bottleneck. Rank highest to lowest on THAT number, and you've found your priority order.",
        "analogy": "Like judging streaming shows by enjoyment per minute, not per season. A tight 90-minute movie can beat a sprawling 10-hour series if it delivers more joy for the time it costs you."
      },
      {
        "type": "quiz",
        "question": "Products X, Y, Z have CM of $4, $5, $10 and use 1, 1, and 5 machine hours each. Which has the BEST CM per machine hour?",
        "options": [
          "Z, because it has the highest CM per unit ($10)",
          "Y, at $5 per machine hour",
          "X, at $4 per machine hour",
          "They're all equal once you adjust"
        ],
        "answer": 1,
        "correctMsg": "Yes! $4/$5/$10 ÷ 1/1/5 = $4, $5, $2 per hour. Y wins at $5/hour, X is next at $4, and flashy Z is actually last at just $2/hour.",
        "wrongMsg": "Watch the division: $10 ÷ 5 hours = only $2/hour for Z. Y gives $5 ÷ 1 = $5/hour — the best. The big per-unit margin fooled you, which is exactly the trap!"
      },
      {
        "type": "teach",
        "title": "Produce to demand, top rank down",
        "body": "Once you've ranked by CM per scarce unit, make your #1 product up to its full demand, then #2, then #3 — pouring the scarce resource down the list until it runs dry. The last product in line usually only gets a partial run with whatever's left over. You don't split evenly; you feed the best earners first.",
        "analogy": "Like loading a moving truck: heaviest-value boxes go in first until it's full. Whatever doesn't fit just doesn't make this trip."
      },
      {
        "type": "quiz",
        "question": "With 5,000 machine hours and demand of 1,000 X / 3,000 Y / 2,000 Z (ranked Y, then X, then Z), what do you produce?",
        "options": [
          "Equal hours split across X, Y, and Z",
          "All 2,000 Z first since it has the highest CM per unit",
          "3,000 Y, then 1,000 X, then 200 Z with the leftover hours",
          "3,000 Y and 2,000 Z, skipping X"
        ],
        "answer": 2,
        "correctMsg": "Perfect! Y uses 3,000h, X uses 1,000h, leaving 1,000h ÷ 5 = 200 Z. You feed the best ranks first and Z gets only a partial run.",
        "wrongMsg": "Follow the ranking: 3,000 Y (3,000h) + 1,000 X (1,000h) = 4,000h used, leaving 1,000h. That's 1,000 ÷ 5 = 200 units of Z. The lowest rank gets the leftovers."
      },
      {
        "type": "teach",
        "title": "The little guy can win",
        "body": "Here's the satisfying twist: a product with a smaller contribution margin per unit can be your top priority if it sips the bottleneck instead of guzzling it. Efficiency on the scarce resource beats raw margin every time. So never count out the 'cheap' product — it might be your quiet MVP.",
        "analogy": "Like a fuel-sipping hatchback beating a thirsty sports car on a road trip with limited petrol. Less flashy per kilometre, but it gets you way further on the same tank."
      },
      {
        "type": "quiz",
        "question": "True to the rules: can a product with a LOWER contribution margin per unit ever be ranked first?",
        "options": [
          "Yes — if it uses very little of the scarce resource, its CM per scarce unit can be highest",
          "No — the highest CM per unit always wins",
          "Only if the company runs out of money",
          "Only if customer demand is unlimited"
        ],
        "answer": 0,
        "correctMsg": "Exactly! That's the whole lesson — X's $4 beats Z's $10 per unit because X uses just 1 hour while Z burns 5. Efficiency on the bottleneck rules.",
        "wrongMsg": "Actually, yes it can! A smaller-margin product that barely touches the scarce resource can earn more per scarce unit — like X ($4, 1 hour) outranking Z ($10, 5 hours)."
      }
    ]
  },
  {
    "id": "t-costing",
    "icon": "📊",
    "title": "Variable vs Absorption Costing",
    "desc": "Crack the one tiny difference between two costing methods — and watch profit numbers suddenly make sense.",
    "steps": [
      {
        "type": "teach",
        "title": "They're 90% the same",
        "body": "Here's the good news before we even start: variable costing and absorption costing agree on almost everything. Both put direct materials, direct labour, and variable overhead into the cost of each unit you make. So most of the heavy lifting is identical — don't let the scary names fool you into thinking these are two totally different worlds.",
        "analogy": "Think of two coffee orders that are both a latte — same espresso, same milk, same cup. They only differ by whether you added one extra shot. Same drink, one tiny tweak."
      },
      {
        "type": "quiz",
        "question": "Which three costs do BOTH variable and absorption costing include in a unit's cost?",
        "options": [
          "Direct materials, direct labour, and variable overhead",
          "Direct materials, fixed overhead, and selling costs",
          "Direct labour, fixed overhead, and variable overhead",
          "Only direct materials and direct labour"
        ],
        "answer": 0,
        "correctMsg": "Exactly! DM, DL, and variable overhead are the shared core — both methods treat these identically. That's why they're 90% the same.",
        "wrongMsg": "Close, but the shared trio is direct materials, direct labour, and variable overhead. Notice fixed overhead isn't in that list — that's the one thing they'll argue about, which is the whole point of this lesson."
      },
      {
        "type": "teach",
        "title": "The one and only difference",
        "body": "Every disagreement between these two methods comes down to a single line item: fixed manufacturing overhead (think rent on the factory, the supervisor's salary). That's it. Once you nail how each method treats fixed OH, you've basically mastered the whole topic.",
        "analogy": "It's like two recipes that are word-for-word identical except one says 'add salt to the dough' and the other says 'sprinkle salt on at the end.' Same ingredient, totally different timing — and that timing is everything here."
      },
      {
        "type": "quiz",
        "question": "What is the ONLY cost that variable and absorption costing treat differently?",
        "options": [
          "Direct materials",
          "Variable overhead",
          "Fixed manufacturing overhead",
          "Direct labour"
        ],
        "answer": 2,
        "correctMsg": "Yes! Fixed manufacturing overhead is the single point of disagreement. Everything else is shared.",
        "wrongMsg": "Not quite — that cost is actually handled the same way by both methods. The one they fight over is fixed manufacturing overhead. Lock that in and the rest falls into place."
      },
      {
        "type": "teach",
        "title": "Variable costing: fixed OH is a 'now' cost",
        "body": "Under variable costing, fixed manufacturing overhead is treated as a period cost — it gets expensed in full this period, no matter how many units you made or sold. It never sneaks into the cost of a unit. So a unit's cost is just the variable stuff added up.",
        "analogy": "It's like your monthly Netflix subscription. You pay it whether you watch 1 show or 50 — it's just a cost of being alive this month, not a cost glued onto each episode you stream."
      },
      {
        "type": "quiz",
        "question": "Using DM $40, DL $30, variable OH $2, and fixed OH $5, what is the unit cost under VARIABLE costing?",
        "options": [
          "$77",
          "$72",
          "$70",
          "$5"
        ],
        "answer": 1,
        "correctMsg": "Spot on — 40 + 30 + 2 = $72. The $5 fixed OH is expensed as a period cost and stays out of the unit cost.",
        "wrongMsg": "Almost! Under variable costing you add only the variable bits: 40 + 30 + 2 = $72. The $5 fixed OH is a period cost, so it does NOT join the unit cost ($77 would be the absorption answer)."
      },
      {
        "type": "teach",
        "title": "Absorption costing: fixed OH rides along",
        "body": "Under absorption costing, each unit 'absorbs' a slice of fixed manufacturing overhead, so fixed OH becomes part of the unit cost. With the same numbers, you add the $5 fixed OH on top: 40 + 30 + 2 + 5 = $77 per unit. The fixed cost now travels with the product.",
        "analogy": "Like a concert ticket where the booking fee is baked into the price instead of shown separately. Every ticket quietly carries a piece of that fixed cost — you can't see it, but it's in there."
      },
      {
        "type": "quiz",
        "question": "With the same figures, what is the unit cost under ABSORPTION costing?",
        "options": [
          "$72",
          "$70",
          "$77",
          "$82"
        ],
        "answer": 2,
        "correctMsg": "Nailed it — 40 + 30 + 2 + 5 = $77. Absorption costing bakes the $5 fixed OH right into each unit.",
        "wrongMsg": "Not quite — absorption costing adds the $5 fixed OH onto the variable $72, giving 40 + 30 + 2 + 5 = $77. The fixed cost rides along inside each unit."
      },
      {
        "type": "teach",
        "title": "Why the profits differ",
        "body": "The profit gap between the two methods equals the change in inventory units multiplied by the fixed OH per unit. Under absorption costing, fixed OH attached to unsold units gets 'parked' in inventory instead of expensed now. So when production is greater than sales (inventory rises), absorption profit is HIGHER than variable, because some fixed OH is deferred in those unsold units.",
        "analogy": "Imagine baking 100 cookies but only selling 80. Absorption costing lets you stash the oven-heating cost of the 20 leftover cookies in the cupboard for later, so this month looks more profitable. Variable costing makes you eat the whole oven bill today."
      },
      {
        "type": "quiz",
        "question": "If a company produces MORE units than it sells (inventory rises), how does absorption profit compare to variable profit?",
        "options": [
          "Absorption profit is higher, because fixed OH is deferred in unsold inventory",
          "Variable profit is higher, because fixed OH is deferred in inventory",
          "They are always exactly equal",
          "Absorption profit is lower, because all fixed OH is expensed immediately"
        ],
        "answer": 0,
        "correctMsg": "Exactly right! When production exceeds sales, absorption costing parks some fixed OH in unsold inventory, so its profit comes out higher than variable.",
        "wrongMsg": "Let's reset: when production beats sales, absorption costing defers some fixed OH inside the unsold units (instead of expensing it all now), so absorption profit ends up HIGHER than variable profit."
      }
    ]
  },
  {
    "id": "t-abc",
    "icon": "🎯",
    "title": "Activity-Based Costing (ABC)",
    "desc": "Stop guessing what your products really cost — ABC follows the money activity by activity.",
    "steps": [
      {
        "type": "teach",
        "title": "Why traditional costing gets sloppy",
        "body": "Traditional costing takes ALL your overhead and smears it on with a single plant-wide rate — usually based on direct labour hours. It's fast and simple, but it assumes every product soaks up overhead the same way, which often isn't true. That's where the cost numbers start to lie a little.",
        "analogy": "Picture splitting a group dinner bill evenly when you ordered a side salad and your friend ordered three cocktails and the lobster. Easy math, but you're quietly overpaying."
      },
      {
        "type": "quiz",
        "question": "How does traditional costing apply overhead to products?",
        "options": [
          "Using one plant-wide rate, like direct labour hours, for all overhead",
          "Using a separate rate for each individual activity",
          "It doesn't apply overhead at all — only direct costs"
        ],
        "answer": 0,
        "correctMsg": "Exactly! One rate (e.g. direct labour hours) spreads ALL overhead across everything — simple, but it ignores how differently products actually use resources.",
        "wrongMsg": "Not quite — that's actually ABC's approach. Traditional costing uses ONE plant-wide rate (like direct labour hours) for all overhead, which is why it can be misleading."
      },
      {
        "type": "teach",
        "title": "What ABC does differently",
        "body": "ABC breaks overhead into multiple activity cost pools — setup, inspection, machining, and so on — and gives each pool its OWN cost driver. Then it charges each product for what it actually used. More pools, more accurate drivers, fairer answer. The trade-off? It's more complex and more expensive to run, not simpler.",
        "analogy": "It's the itemized restaurant bill: you pay for YOUR salad, your friend pays for the lobster and cocktails. More line items to track, but everyone pays their true share."
      },
      {
        "type": "quiz",
        "question": "Compared to traditional costing, ABC uses…",
        "options": [
          "Fewer pools and is simpler to run",
          "More cost pools and more accurate drivers, but is more complex",
          "The same number of pools, just renamed"
        ],
        "answer": 1,
        "correctMsg": "You got it! ABC uses MORE cost pools and MORE accurate drivers. That accuracy comes at the cost of extra complexity — it's not the easy option.",
        "wrongMsg": "Careful — ABC is the more detailed approach: MORE pools and MORE accurate drivers. The catch is it's more complex and costly, not simpler."
      },
      {
        "type": "teach",
        "title": "The 4 steps of ABC",
        "body": "There's a clean recipe here. (1) Pool overhead by activity. (2) Activity rate = pool cost ÷ total driver volume. (3) Applied overhead = rate × that product's driver usage. (4) Unit cost = DM + DL + (total applied OH ÷ units). Nail the order and the numbers fall into place.",
        "analogy": "Like a coffee shop costing each drink: group the milk-steaming costs, work out cost per steam, charge each latte for its steams, then add beans and barista time to get the price per cup."
      },
      {
        "type": "quiz",
        "question": "In ABC, how do you calculate an activity rate?",
        "options": [
          "Total driver volume ÷ pool cost",
          "Pool cost × total driver volume",
          "Pool cost ÷ total driver volume"
        ],
        "answer": 2,
        "correctMsg": "Spot on! Activity rate = pool cost ÷ total driver volume. That gives you a per-driver-unit price you can then charge each product.",
        "wrongMsg": "Flip it around: it's pool cost ÷ total driver volume. Dividing the pool's dollars by the total driver units gives the cost per unit of driver."
      },
      {
        "type": "teach",
        "title": "Putting a rate to work",
        "body": "Once you have a rate, the rest is plug-and-play. Say a parts-handling pool costs $225,000 and there are 1,500 part types total: $225,000 ÷ 1,500 = $150 per part type. A product is then charged $150 for each part type it uses. Compare that to a plant-wide rate like $912,000 ÷ 40,000 DLH = $22.80 per direct labour hour — one blunt number for everything.",
        "analogy": "The $150-per-part-type rate is a per-item price tag at the deli counter — you pay for exactly the slices you take, not a flat 'food fee' at the door."
      },
      {
        "type": "quiz",
        "question": "A parts pool of $225,000 is spread over 1,500 part types. What's the activity rate?",
        "options": [
          "$150 per part type",
          "$1,500 per part type",
          "$22.80 per part type"
        ],
        "answer": 0,
        "correctMsg": "Nailed it! $225,000 ÷ 1,500 = $150 per part type. Now any product gets charged $150 for each part type it actually uses.",
        "wrongMsg": "Run the division: $225,000 ÷ 1,500 = $150 per part type. ($22.80 was the plant-wide DLH rate from a different example — easy to mix up!)"
      },
      {
        "type": "teach",
        "title": "Who was getting overcharged?",
        "body": "Here's the punchline. Traditional costing OVER-costs simple, high-volume products and UNDER-costs complex, low-volume ones — because the complex products quietly hog setups, inspections and special handling. ABC corrects this by tracing those activities to whoever actually triggers them. Suddenly the 'cheap' complex product reveals its true, higher cost.",
        "analogy": "The high-maintenance friend who needs three custom orders and special requests was riding on the even-split bill. ABC hands them their real tab — and gives the easy-going salad-orderer a refund."
      },
      {
        "type": "quiz",
        "question": "Under traditional costing, which products tend to be UNDER-costed?",
        "options": [
          "Simple, high-volume products",
          "Complex, low-volume products",
          "All products equally"
        ],
        "answer": 1,
        "correctMsg": "Yes! Complex, low-volume products are under-costed (and simple high-volume ones over-costed). ABC fixes the distortion by tracing activities to their real users.",
        "wrongMsg": "Other way around: complex, LOW-volume products get under-costed because they secretly consume lots of activities. Simple high-volume products are the ones over-costed. ABC corrects both."
      }
    ]
  },
  {
    "id": "t-support",
    "icon": "🏢",
    "title": "Support Department Allocation",
    "desc": "Learn how to fairly push support costs onto the departments that actually make stuff — no scary math, promise.",
    "steps": [
      {
        "type": "teach",
        "title": "Why we allocate at all",
        "body": "Support departments like IT, Maintenance, and HR don't actually make any product you can sell. But they still cost money, and that money has to land somewhere. So we 'allocate' their costs onto the PRODUCTION departments — the ones that genuinely build the goods — so every product carries its fair share.",
        "analogy": "Think of a share-house. Nobody can sell the Wi-Fi or the cleaning service, but everyone benefits, so you split those bills across the housemates who live there."
      },
      {
        "type": "quiz",
        "question": "Why do we allocate support department costs to production departments?",
        "options": [
          "Because support departments don't make sellable product, but their costs still need a home",
          "Because production departments have more staff",
          "Because the tax office requires support departments to disappear"
        ],
        "answer": 0,
        "correctMsg": "Exactly! Support depts (IT, HR, Maintenance) cost money but make nothing sellable, so their costs get pushed onto the production depts that do.",
        "wrongMsg": "Not quite — it's not about headcount or tax rules. The real reason: support depts make nothing you can sell, so their costs must be shifted onto the production depts that actually make product."
      },
      {
        "type": "teach",
        "title": "The Direct Method",
        "body": "The Direct method is the simplest: each support department's cost is allocated ONLY to production departments. It completely ignores any services support depts give each other — like IT fixing Maintenance's computers. Because we ignore those, the denominator we divide by only includes production-department driver totals.",
        "analogy": "It's like splitting the pizza bill only among the friends who actually ate pizza — even if the delivery driver grabbed a slice, you just pretend they didn't."
      },
      {
        "type": "quiz",
        "question": "Under the Direct method, when allocating one support department's cost, what do we IGNORE?",
        "options": [
          "Any services that support departments provide to each other",
          "All of the production departments",
          "The total cost of the support department"
        ],
        "answer": 0,
        "correctMsg": "Spot on! Direct method ignores support-to-support services entirely — costs flow straight to production depts only.",
        "wrongMsg": "Careful — we definitely keep the production depts and the support dept's cost. What we throw away is the support-to-support services (like IT helping HR). That's what makes it 'direct'."
      },
      {
        "type": "teach",
        "title": "Direct Method in action",
        "body": "Let's run the numbers. Support dept S2 has $30,000 to allocate, based on floor space. Production depts have P1 = 20,000, P2 = 30,000, P3 = 50,000 sq m — total 100,000. Notice we ignore S1's space because it's another support dept. So P2 gets 30,000 × (30,000 ÷ 100,000) = $9,000.",
        "analogy": "It's like splitting rent by how big each person's bedroom is — you only count the actual bedrooms, not the hallway closet nobody sleeps in."
      },
      {
        "type": "quiz",
        "question": "Using S2's $30,000 allocated by space (P1 20,000, P2 30,000, P3 50,000 sq m, ignoring S1), how much goes to P2?",
        "options": [
          "$9,000",
          "$10,000",
          "$6,000",
          "$30,000"
        ],
        "answer": 0,
        "correctMsg": "Nailed it! 30,000 × (30,000 ÷ 100,000) = $9,000. You divided by the production totals only — exactly right.",
        "wrongMsg": "Close, but check the denominator: it's the production total 100,000 (20k+30k+50k). So 30,000 × (30,000 ÷ 100,000) = $9,000. The trick is ignoring S1's space."
      },
      {
        "type": "teach",
        "title": "The Step-Down Method",
        "body": "Step-Down is a bit fairer than Direct. You allocate support departments in a sequence — usually the one that serves the most other departments goes first. Its cost spreads to everyone below it (including other support depts), but it's one-way only: once a department is allocated and 'closed', nothing ever flows back to it.",
        "analogy": "Like a relay race where you can only pass the baton forward. Once you've handed it off and stepped off the track, no one can pass it back to you."
      },
      {
        "type": "quiz",
        "question": "What makes the Step-Down method different from the Direct method?",
        "options": [
          "It allocates support depts in sequence, letting earlier ones partly serve other support depts — but never flowing back",
          "It allocates everything back and forth fully between all departments",
          "It ignores production departments completely"
        ],
        "answer": 0,
        "correctMsg": "Yes! Step-Down goes in order (biggest server first), allows one-way flow into other support depts, but nothing comes back. A nice middle ground.",
        "wrongMsg": "Not quite. Full back-and-forth is the Reciprocal method. Step-Down is one-way only: it allocates in sequence and lets earlier support depts serve later ones, but nothing ever flows back."
      },
      {
        "type": "teach",
        "title": "The Reciprocal Method",
        "body": "Reciprocal is the most accurate method because it recognises the full, two-way relationships — IT serves Maintenance AND Maintenance serves IT, both directions, fully. The catch is it needs simultaneous equations, so it's rarely done by hand and is usually left to software.",
        "analogy": "Like two friends who both Venmo each other for shared stuff all month — to settle up perfectly you'd need to untangle who owes whom both ways. Accurate, but you'd reach for a calculator (or an app)."
      },
      {
        "type": "quiz",
        "question": "Which statement best describes the Reciprocal method?",
        "options": [
          "Most accurate, captures full two-way service between support depts, rarely done by hand",
          "Simplest method, ignores all inter-support services",
          "One-way only, with nothing flowing back"
        ],
        "answer": 0,
        "correctMsg": "Perfect! Reciprocal models the full two-way relationships, making it the most accurate — but the simultaneous equations mean it's rarely hand-calculated.",
        "wrongMsg": "Heads up — ignoring inter-support services is Direct, and one-way-only is Step-Down. Reciprocal is the full two-way, most accurate method that's rarely done by hand."
      }
    ]
  },
  {
    "id": "t-budget",
    "icon": "📅",
    "title": "Budgeting",
    "desc": "Turn the scary \"budget\" word into a few friendly formulas you can nail in your sleep.",
    "steps": [
      {
        "type": "teach",
        "title": "A budget is just a plan in numbers",
        "body": "Deep breath. A budget isn't some intimidating spreadsheet wizardry, it's literally a plan written in numbers instead of words. Instead of saying 'we'll probably sell a lot and buy enough stuff,' a budget pins it down so everyone knows the game plan ahead of time.",
        "analogy": "It's like planning a road trip: you don't just drive and hope, you map the route, guess the petrol, and pack snacks. A budget is that trip plan, but for a business's money."
      },
      {
        "type": "quiz",
        "question": "What's the simplest way to describe what a budget actually is?",
        "options": [
          "A report of what already happened last year",
          "A plan expressed in numbers",
          "A list of a company's debts"
        ],
        "answer": 1,
        "correctMsg": "Exactly! A budget is a plan in numbers, looking forward and pinning down the game plan before it happens.",
        "wrongMsg": "Close, but that's looking backward. A budget faces forward, it's a plan expressed in numbers, mapping out what you intend to do before you do it."
      },
      {
        "type": "teach",
        "title": "The purchases formula (in units)",
        "body": "Here's the one formula to tattoo on your brain: Purchases = budgeted sales + desired ending inventory − beginning inventory. You buy enough to cover what you'll sell PLUS what you want left on the shelf, then subtract what you already had sitting there. Don't buy what you already own!",
        "analogy": "Think of stocking your fridge for the week: buy what you'll eat (sales) + what you want left over (ending inventory) − what's already in there (beginning inventory). No point buying milk you already have."
      },
      {
        "type": "quiz",
        "question": "May sales are 1,575 units, May desired ending inventory is 412, and beginning inventory is 315. How many units should be purchased in May?",
        "options": [
          "1,478 units",
          "1,672 units",
          "2,302 units",
          "1,575 units"
        ],
        "answer": 1,
        "correctMsg": "Nailed it! 1,575 + 412 − 315 = 1,672 units. You added what you'll sell and want left, then subtracted what you already had.",
        "wrongMsg": "Almost! The formula is sales + desired ending − beginning: 1,575 + 412 − 315 = 1,672 units. It's easy to subtract the wrong piece, just remember you only subtract what you already own."
      },
      {
        "type": "teach",
        "title": "Beginning inventory = last month's ending",
        "body": "This trips people up but it's beautifully simple: whatever you had left at the END of one month is exactly what you START the next month with. Nothing magically appears or vanishes overnight. So a month's beginning inventory just equals the prior month's ending inventory.",
        "analogy": "It's like your phone battery. However much charge you go to bed with is exactly what you wake up with (assuming nothing's plugged in). Last night's ending = this morning's beginning."
      },
      {
        "type": "quiz",
        "question": "If April's ending inventory is 412 units, what is May's beginning inventory?",
        "options": [
          "0 units, it resets each month",
          "412 units",
          "It depends on May's sales"
        ],
        "answer": 1,
        "correctMsg": "Yes! May begins with exactly what April ended with: 412 units. Stock doesn't vanish overnight.",
        "wrongMsg": "Not quite, inventory carries straight over. Whatever April ends with (412 units) is precisely what May starts with. Last month's ending = this month's beginning."
      },
      {
        "type": "teach",
        "title": "From units to dollars",
        "body": "Once you know how many units to buy, getting the dollar figure is the easy part: just multiply units by the cost per unit. First figure out the units with the purchases formula, THEN turn it into money. One step at a time.",
        "analogy": "It's like a coffee run for your mates: first count the cups (units), then multiply by the price each. 6 coffees × $5 = $30. Count first, then times the price."
      },
      {
        "type": "quiz",
        "question": "June sales are 1,650 units, desired ending inventory 425, beginning inventory 412, and cost is $125 per unit. What are June's dollar purchases?",
        "options": [
          "$206,250",
          "$207,875",
          "$209,625",
          "$215,625"
        ],
        "answer": 1,
        "correctMsg": "Perfect! Units = 1,650 + 425 − 412 = 1,663, then 1,663 × $125 = $207,875. Units first, dollars second.",
        "wrongMsg": "So close! Do units first: 1,650 + 425 − 412 = 1,663 units. Then multiply: 1,663 × $125 = $207,875. The trap is multiplying before sorting out the units."
      },
      {
        "type": "teach",
        "title": "Participative budgeting",
        "body": "Participative budgeting means employees throughout the organisation help set the budget, instead of bosses dictating numbers from the top. It's a bottom-up approach, and because people had a say, they tend to actually buy into the targets and feel ownership.",
        "analogy": "It's the difference between a parent dictating the family holiday vs everyone voting on where to go. When you helped pick the destination, you're way more excited to make the trip work."
      },
      {
        "type": "quiz",
        "question": "What best describes participative budgeting?",
        "options": [
          "Senior management sets all targets and hands them down",
          "Employees throughout the organisation help set the budget",
          "An outside consultant builds the budget alone"
        ],
        "answer": 1,
        "correctMsg": "Spot on! Participative budgeting is bottom-up: employees across the org help set the targets, which builds real buy-in.",
        "wrongMsg": "That's the top-down style. Participative budgeting is the opposite, employees throughout the organisation help set the budget, so they feel ownership over the targets."
      },
      {
        "type": "teach",
        "title": "Budgetary slack (the sneaky one)",
        "body": "Budgetary slack, also called padding, is when someone deliberately makes the budget too easy by understating expected revenue or overstating expected costs. Why? So the targets are a breeze to beat and they look like a hero later. Sneaky, but very human, and examiners love testing it.",
        "analogy": "It's like telling your parents the assignment is due Friday when it's really due next Tuesday, so you've got comfy wiggle room and look super on top of it. That cushion you secretly built in is the slack."
      },
      {
        "type": "quiz",
        "question": "A manager expects $500,000 in revenue but budgets only $400,000, so the target is easy to beat. What is this?",
        "options": [
          "Participative budgeting",
          "Budgetary slack (padding)",
          "Beginning inventory"
        ],
        "answer": 1,
        "correctMsg": "Exactly! Understating revenue to make the target easy to beat is classic budgetary slack, also known as padding.",
        "wrongMsg": "Not quite. Deliberately understating revenue (or overstating costs) to make a target easy to beat is budgetary slack, or padding. That secret cushion is the giveaway."
      }
    ]
  }
];
